### PR TITLE
RFM22B Module frequency settable

### PR DESCRIPTION
**Pull request by sfabris**
Guys, these are my first C line of codes since about 20 years, so sorry for lots of things, my first PR in github etc. so be gentle :-)

This is a first try to implement a "configurable" frequency for RFM22B modules in openlrs.

Same approach should be used also for pios_rfm22b.

Code compiles but I have no hardware with me right now for testing.

### CODE REVIEW

**Comment by peabody124** [comment]
jenkins: add to whitelist

**Comment by peabody124** [comment]
jenkins: test this please

**Comment by jhitesma** [comment]
RFM22BCONFIG_FREQUENCY_868  be RFM22BCONFIG_FREQUENCY_915 on 1104 of flight/PiOS/Common/pios_openlrs.c

(still not used to github and not sure if this is the best place to put this)

**Comment by sfabris** [comment]
@peabody124 module frequency should go to hwsparky, as you suggested in IRC.
Unfortunately, I don't know if is possible / safe to access  hwsparky structures from pios_openlrs.c...

**Comment by mlyle** [comment]
Fails build on some boards during jenkins build:

    10:32:19 /var/lib/jenkins/workspace/taulabs-pr-linux-amd64/build/fw_revomini/pios_openlrs.o: In function `PIOS_OpenLRS_Init':
    10:32:19 /var/lib/jenkins/workspace/taulabs-pr-linux-amd64/flight/PiOS/Common/pios_openlrs.c:1090: undefined reference to `RFM22BConfigInitialize'
    10:32:19 /var/lib/jenkins/workspace/taulabs-pr-linux-amd64/build/fw_revomini/pios_openlrs.o: In function `RFM22BConfigGet':
    10:32:19 /var/lib/jenkins/workspace/taulabs-pr-linux-amd64/build/uavobject-synthetics/flight/rfm22bconfig.h:67: undefined reference to `RFM22BConfigHandle'

**Comment by mlyle** [comment]
I am totally sorry, I had forgotten about this pull when I duplicated your work.  I will be working in the coming days to take the best of both.

(Ended up reimplementing this because someone on IRC was asking for it).

**Pull request closed without merging**
