### PR TITLE
Sparky: enable external magnetometer support

### PR DESCRIPTION
**Pull request by peabody124**

### CODE REVIEW

**Comment by peabody124** [comment]
jenkins: test this please

**Comment by peabody124** [comment]
@jihlein have you had a chance to test this?

**Comment by jihlein** [comment]
Bench tested only.  Was able to switch to external mag and change it's orientation as expected, and switch back to internal mag.  No flight test as of yet. 

Date: Wed, 11 Feb 2015 18:07:48 -0800

**Comment by peabody124** [comment]
Let me know if you get a chance to flight test and then it can merge

**Comment by jihlein** [comment]
Will do, it will be a little while as I will be out of town for the next week.
-JI

Date: Sun, 15 Feb 2015 14:49:07 -0800

**Comment by peabody124** [comment]
@jihlein ping on testing :D

**Comment by jihlein** [comment]
I've got something crossed up in GIT I think.  Whatever the issue is, I can't get the Sparky board to recognize the Spektrum satellite receiver.  In fact, none of my boards (Quanton, Sparky, AQ32, Naze32Pro) will talk to a satellite right now.
I tried the 31 January 2015: New Release 20150131-4082e9d8 release with the same issue, if I can't sort things out I'm going to go back to 26 October 2014: New Release 20141026-1f8fa2fe as that was the last time I setup a satellite RX with Sparky.  I know I had satellite receivers working with both Sparky and Naze32Pro.
Don't know what's going on, feel like I'm missing something obvious.......
-JI

Date: Wed, 25 Feb 2015 09:05:51 -0800

**Comment by peabody124** [comment]
I'll go ahead and merge this since you bench tested it previously.

**Comment by jihlein** [comment]
Out of curiosity, why the change from 400 kHz flexi port I2C speed to 50 kHz?  Seems awful slow.  400 kHz worked fine in my testing.

**Comment by peabody124** [comment]
I was trying to be conservative. With longer cables on my BGC I've found that helps (the MPU9150 is moving more traffic though). As slow as possible is probably a reasonable goal for that, unless I'm missing something.

**Comment by jihlein** [comment]
As long as it doesn't bog down the FC loop, it's probably better slower.  Though the flight control environment is probably not as harsh as the brushless gimbal where the sensor and it's I2C lines are in closer proximity to 3 brushless motors.........
It surprises me more brushless gimbal designs have not made use of the F3 and it's I2C filtering capabilities to help with the I2C noise problem.

Date: Mon, 16 Mar 2015 18:04:42 -0700

**Pull request merged**
