### PR TITLE
OpenLRS reliability improvements

### PR DESCRIPTION
**Pull request by peabody124**
This improves the timing of the OpenLRS code and makes it better stay in sync with
the channel hopping.

### CODE REVIEW

**Comment by peabody124** [comment]
We might also want to merge this fix into master, then we can update the last release and avoid this bug.

**Comment by kubark42** [comment]
@peabody124, I know it's a PITA, but since jenkins is down could you confirm that this passes all build tests?

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
```19:28:11 /var/lib/jenkins/workspace/taulabs-pr-linux-amd64/flight/PiOS/Common/pios_openlrs.c: In function 'pios_openlrs_task':
19:28:11 /var/lib/jenkins/workspace/taulabs-pr-linux-amd64/flight/PiOS/Common/pios_openlrs.c:1207:63: error: 'FALSE' undeclared (first use in this function)
19:28:11    if (PIOS_Semaphore_Take(openlrs_dev->sema_isr, delay_ms) == FALSE) {
19:28:11                                                                ^
19:28:11 /var/lib/jenkins/workspace/taulabs-pr-linux-amd64/flight/PiOS/Common/pios_openlrs.c:1207:63: note: each undeclared identifier is reported only once for each function it appears in
19:28:11 make[1]: *** [/var/lib/jenkins/workspace/taulabs-pr-linux-amd64/build/fw_revomini/pios_openlrs.o] Error 1
19:28:11 make: *** [fw_revomini_tlfw] Error 2
19:28:11 make: *** Waiting for unfinished jobs....```

**Comment by peabody124** [comment]
@kubark42 thanks for being fastidious since it didn't pass build tests :) fixed the case of "FALSE" so it should

**Comment by kubark42** [comment]
jenkins agrees!

**Comment by peabody124** [comment]
@mlyle is this good to merge with you? Positive test results were reported in #1796 and I'd love to get that bug closed

**Comment by mlyle** [comment]
I have no objective but have not reviewed.

**Comment by mluessi** [comment]
Lets merge this; it fixes a bug and we already have one positive test report, merging it will give it more exposure before the next release.

**Comment by mlyle** [comment]
Looks good in review.

**Pull request merged**
