### PR TITLE
Simulation: make a standalone target

### PR DESCRIPTION
**Pull request by peabody124**
The simulation code really has nothing to do with any of the board targets
and was only grouped together for historical reasons. This makes a standalone
simulation target

```make simulation```

In a separate PR we can probably drop the revolution (full) hardware entirely.

### CODE REVIEW

**Comment by peabody124** [comment]
@mlyle let me know what you think of this. One downside of keeping the old macro expansion code is that the simulation ends up in ```build/sim_simulation_posix```. It probably is worth dropping that expansion code, don't you think?

**Comment by mlyle** [comment]
sure, I like shorter names, it can become sim_posix.  Once it builds it sounds good :)

**Comment by mlyle** [comment]
(The reason this is failing is, I think, because jenkins is explicitly making sim_posix_revolution).

**Comment by peabody124** [comment]
Grr jenkins

**Comment by peabody124** [comment]
Closing this. Superseded by #1631

**Pull request closed without merging**
