### PR TITLE
Mpl ccache: Just the ccache related changes

### PR DESCRIPTION
**Pull request by mlyle**
I'm learnin'.  Sane pull requests for review.

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins: test this please

**Comment by peabody124** [comment]
jenkins: test this please

**Comment by elafargue** [comment]
OK, the stats below speak for themselves. But: the PR assumes that ccache is in /usr/bin - on a Mac, it might very well be in /opt/local/bin or other places depending on how it was installed. I suggest changing the way you detect ccache with:

```
ifneq ($(shell which ccache), "")
        CCACHE=ccache
else
        CCACHE=
endif
```

With this patch, on a clean build, on a 'late 2013' MBP with 16GB RAM and 2.7GHz Core i7:
next branch:
time make -j 5 all_fw
real	2m30.943s

* checkout PR
$make all_clean
$ time make -j 5 all_fw
real	2m48.400s
user	11m4.548s
sys	2m1.509s

$make all_clean
$make -j 5 all_fw
real	0m13.006s
user	0m27.851s
sys	0m19.131s

Nice one !

**Comment by mlyle** [comment]
Good idea to just use which for the probe; now it's in.  I also noted why it doesn't help GCS builds on OSX in a comment in the project file.

**Comment by peabody124** [comment]
I see similar improvements in build time on my end for flight firmware

**Comment by jbtecno** [comment]
http://www.google.pt/imgres?imgurl=http://www.globalwatersolutions.com/uploads/images/EnergySavingSolution.jpg&imgrefurl=http://www.globalwatersolutions.com/index.php?page%3Denergy-saving-solutions&h=409&w=423&tbnid=x1axuUwF9gLN6M:&zoom=1&docid=eZqcIv7yqaez7M&ei=iFshVc-oA6Wt7Abp6oGoCg&tbm=isch&ved=0CDEQMygTMBM

**Pull request merged**
