### PR TITLE
gcs/translations: include all appropriate qt translation files on all platforms

### LINKED ISSUE #1943: gcs: Translations do not show in preferences dialog box
I believe this is because the QT translation files are missing.  We have code to package stuff up but it's only used on win32.  Investigating further.

```
openat(AT_FDCWD, "/home/mlyle/taulabs_20150912_125701_2634cd1_linux_amd64/gcs/share/taulabs/translations", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 27
statfs("/home/mlyle/taulabs_20150912_125701_2634cd1_linux_amd64/gcs/share/taulabs/translations/", {f_type="EXT2_SUPER_MAGIC", f_bsize=4096, f_blocks=9699999, f_bfree=5431684, f_bavail=4974886, f_files=2464320, f_ffree=2025184, f_fsid={26425843, -9213094}, f_namelen=255, f_frsize=4096}) = 0
getdents(27, /* 9 entries */, 32768)    = 320
getdents(27, /* 0 entries */, 32768)    = 0
close(27)                               = 0
stat("/home/mlyle/taulabs_20150912_125701_2634cd1_linux_amd64/gcs/bin/translations/qt_de.qm", 0x7ffebdc66220) = -1 ENOENT (No such file or directory)
stat("/home/mlyle/taulabs_20150912_125701_2634cd1_linux_amd64/gcs/share/taulabs/translations/qt_de.qm", 0x7ffebdc66220) = -1 ENOENT (No such file or directory)
stat("/home/mlyle/taulabs_20150912_125701_2634cd1_linux_amd64/gcs/bin/translations/qt_es.qm", 0x7ffebdc66220) = -1 ENOENT (No such file or directory)
```

### PR DESCRIPTION
**Pull request by mlyle**
Fixes #1943 

Needs verification on packaging, etc.

### CODE REVIEW

**Comment by mlyle** [comment]
Verified good on amd64, packaged by me.

**Comment by mlyle** [comment]
Verified good on OSX.  I suggest merge.

**Comment by mlyle** [comment]
#1937 should also merge.

**Comment by tracernz** [comment]
On the face of it this looks good. The original script to copy these files dates back to 2010. I wonder why they only did it on win32? Just did a test build on x64 Linux and there are several languages available so this is definitely working. 

Maybe after this lands the prospect of translating some more of the strings will become more appealing for some of our non-native english speaking users.

**Comment by peabody124** [comment]
testing on OSX

**Comment by peabody124** [comment]
Merging, although the quality of our translations make this quite ... underwhelming so I'm not totally sure it's a feature to distribute them ...

I know someone once mentioned a webpage where you can somehow upload the language files and communities will work on translations for open source projects.

**Pull request merged**
