### PR TITLE
Build: (partially) dedup firmware makefiles

### PR DESCRIPTION
**Pull request by mlyle**
There was a lot of boilerplate that was shared between different
firmware makefiles.  (With very little functional difference, like
conditionals on firmware output formats).  This commit unifies that
boilerplate.

There is still a lot of build system duplication, and I intend to keep
working in this area as a background task.

### CODE REVIEW

**Comment by guilhermito** [comment]
Looks good

**Comment by peabody124** [comment]
jenkins: test this please

**Comment by peabody124** [comment]
this is a good step towards #1274

**Comment by peabody124** [comment]
jenkins: test this please

**Comment by lilvinz** [comment]
jenkins: test this please

**Pull request merged**
