### PR TITLE
python: open telemetry in binary format

### PR DESCRIPTION
**Pull request by mlyle**
Fixes issues on windows where telemetry is truncated or empty.

### CODE REVIEW

**Comment by kubark42** [comment]
@mlyle I can't test this on Windows, but it looks sane to me. I'll merge it tomorrow if there are no other comments.

**Comment by jihlein** [comment]
Tested it on Windows 7 64 bit. Worked fine for me.

**Comment by kubark42** [comment]
@jihlein Is this fix related to your comment in https://github.com/TauLabs/TauLabs/issues/1971#issuecomment-144874595?

**Comment by jihlein** [comment]
Yes it is.

**Comment by kubark42** [comment]
Passes jenkins, confirmed to fix bug, impossible to affect flight or ground station functionality. Merging.

**Pull request merged**
