### PR TITLE
VtolPathFollower: immediately start rising to target alt

### PR DESCRIPTION
**Pull request by peabody124**
From https://github.com/d-ronin/dRonin/pull/279

### CODE REVIEW

**Comment by kubark42** [comment]
@peabody124 did you want to respond to @pug398 or is that answered elsewhere?

**Comment by pug398** [comment]
The question was aimed at the fact RTH was in a state of flux and due to events was left in an unfinished state. If at 15m altitude when triggered it would climb 1.5 m and all was good. If at extremely low altitude when triggered it would climb 1.5m and then sit there for 10s. This could lead to a condition of say sitting in the middle of a highway 3m off the ground for 10 seconds without any control. I would say set it back like it was which worked ok or adopt new RTH fsm.

**Comment by peabody124** [comment]
Yeah I hadn't replied cause i need to go throught the logic and run some simulations. As far as I know there is no problem with our current code so don't want to merge this until confirmed ok.

**Comment by mlyle** [comment]
Project level copyright notices.

**Comment by peabody124** [comment]
@mlyle there are none from this PR that I see https://github.com/mlyle/dronin/blob/f3b3b8c6dcd8af87f1e5f98c79381918b2d21d7e/flight/Modules/VtolPathFollower/vtol_follower_fsm.c

**Comment by mlyle** [comment]
It was added 5 days later.

If you want, we can just go ahead and put the no-redis notice on all files on dRonin now along with a copyright 2016 to avoid any confusion in the future.. We've avoided doing that to avoid confusion of attribution and to avoid excess conflict, but would be well within our legal rights to do so, and it'd avoid a lot of the conflicts we've had to deal with multiple PRs updating the line.  It would ensure all future changes are covered, but I'd hope you'd include the project-level copyright notices in good faith.

**Comment by peabody124** [comment]
@kubark42 tested in simulation. good to merge.

**Pull request merged**
