### PR TITLE
packaging: QML PFD: work around QTBUG-42954

### PR DESCRIPTION
**Pull request by mlyle**

### CODE REVIEW

**Comment by mlyle** [comment]
Added fix for welcome screen.

**Comment by peabody124** [comment]
Can you see if this is needed with #1704? That might be a better solution if they fixed the packaging bug.

**Comment by mlyle** [comment]
This is definitely an interim fix/hack.  It should not be needed with 5.4.2 or 5.5.0.

It's just a question of risk-- does picking up QT 5.5 introduce new issues?  The OpenGL build will break on windows assuming the QT 5.5 is OpenGL dynamic like I think it is.  I have a branch somewhere with most of the required changes that I could prepare and submit.  Alternatively we could go to QT 5.4.2 which should fix this and be less invasive.

In either case it'd take Jenkins changes.

**Comment by peabody124** [comment]
I can make some test 5.5 builds tomorrow and we can see if they have breakage. If so I agree 5.4.2 is better.

**Comment by mlyle** [comment]
Issue #1442

**Comment by peabody124** [comment]
This works. Using this until we upgrade to either 5.4.2 or 5.5. Then we should remember to revert it.

**Pull request merged**
