### PR TITLE
MSP support for quanton

### PR DESCRIPTION
**Pull request by dustin**

### CODE REVIEW

**Comment by tracernz** [comment]
Looks good!

**Comment by mluessi** [comment]
Someone click merge please :)

**Comment by mlyle** [comment]
Ideally someone would try it first...

**Comment by mluessi** [comment]
Ooops, yes, good idea. Somehow I had assumed this was tested, but it may not be.

**Comment by dustin** [comment]
@mluessi No, I don't have a quanton -- someone came about with interest, so I made this change and hope we can get it tested.

**Comment by kubark42** [comment]
@dustin Thanks a lot for doing this! Do you think you could edit your original PR and add a bit of detail? It's super helpful for documentation purposes since there might be readers who aren't intimately familiar with our codebase. We especially like to see submitters say on what boards the PR has been tested, e.g. @mlyle is constantly saying if a PR has been bench tested, flown, etc...

I'll try to test this ASAP. I'm feeling kind of guilty that the PR queue is backing up...

**Comment by dustin** [comment]
@kubark42 not sure what you want documented.  I'm unfortunately too familiar with the topic to see what isn't obvious.  :)

**Comment by kubark42** [comment]
Heh, I get what you mean! For starters, the fact that this hasn't been tested is a good tidbit. But also, what is MSP? (I personally know what it is, but these PRs are hugely useful as documentation so I never assume a reader 5 years from now will know what it refers to.) For instance, in https://github.com/TauLabs/TauLabs/pull/1999, you gave enough info for someone to start digging deeper and maybe piece together the information.

Not getting on your case about this. Curating documentation is important to me, so I might be a little more vocal about "pleeeeeease" than most. :)

**Comment by dustin** [comment]
Not at all.  I'm like making good commits.

**Comment by kubark42** [comment]
Thanks!

I recently gave a talk in Boston called "Git is History". The whole talk was about how I see git and PRs as answering the important five questions: Who, What, Where, Why, When. Git automatically takes care of the Who, Where, and When, so that's 60% of the job already done! 

It was largely based off my experiences tracking Tau Labs as I was also developing code internally that had to be able to mesh smoothly back into Tau Labs.

**Comment by mlyle** [comment]
@dustin might be able to teach us a thing or two about using git, too... https://github.com/dustin

**Comment by dustin** [comment]
@kubark42 Yeah, I get really frustrated with bad commits.  Whenever I'm investigating a problem, I often track it back down to a gigantic code dump that says "changed stuff" or something.

"Who" is often lost in some of these which is unfortunate.  When we converted memcached to git, I went back through many years of history to dig out all of the real authors of changes (e.g. who was 'Bob' who would've been touching this part of the code working with Brad on the mailing list around this time).  Rewrote everything with proper author and committer and ended up with a pretty nice chunk of history.

I do like well kept history.

**Comment by dustin** [comment]
TEST_STATUS:  Untested.

(It builds, ship it.)

I don't have a quanton, but have someone who's interested who can hopefully look shortly.  Anyone else is welcome to, though.

**Comment by peabody124** [comment]
I'm ok to merge this based on code review if no one is around to test it. It uses the HAL system so is pretty straightforward. Any objections?

**Comment by kubark42** [comment]
None.

**Comment by lolorc** [comment]
sorry I'm at least 7 days late, just bench tested it. Haven't tried it with data from gps and batmon modules tho. but i guess it should be fine.

**Comment by dustin** [comment]
Thanks for testing that out.  User's just trying to pick it up.

**Pull request merged**
