### PR TITLE
Logging: increase stack to 1200 bytes.

### LINKED ISSUE #1521: [chibios] quanton reboots when arming and connected to gcs and logging enabled
setup is quanton, latest bootloader, latest fw from next.
Settings have been erased, i've just re-imported input/output settings so I can arm.
One module enabled : logging

Connect FC to gcs (usb) then arm => the fc reboots
Arm then connect to gcs => the fc reboots

seems ok with logging disabled.

### PR DESCRIPTION
**Pull request by lolorc**
Thanks James, increasing stack size did really fix #1521

### CODE REVIEW

**Comment by peabody124** [comment]
jenkins: add to whitelist

**Comment by peabody124** [comment]
jenkins: test this please

**Comment by lilvinz** [comment]
jenkins: test this please

**Comment by lilvinz** [comment]
jenkins: test this please

**Pull request merged**
