### PR TITLE
GCS/AutoTune-Use different forum thread for posting

### PR DESCRIPTION
**Pull request by mlyle**
Rescue this commit as it's said to be necessary now.  Needs test.

### CODE REVIEW

**Comment by mlyle** [comment]
#1894

**Comment by mlyle** [comment]
Tested and confirmed to work: http://forum.taulabs.org/viewtopic.php?f=27&t=268&start=100#p6951

**Comment by tracernz** [comment]
Trivial and pretty clearly correct.

**Comment by mlyle** [comment]
Merging based on test and feedback (also not my change).

**Pull request merged**
