### PR TITLE
GCS/Quazip Lib: Updated and moved to separate dir

### PR DESCRIPTION
**Pull request by PTDreamer**

### CODE REVIEW

**Comment by peabody124** [comment]
This is the library used for uploading/downloading partitions. Have you rechecked it works?

**Comment by PTDreamer** [comment]
Don't merge, build is broken on win

**Comment by PTDreamer** [comment]
Tested on windows

**Comment by PTDreamer** [comment]
Please review

**Comment by PTDreamer** [comment]
Merging tomorrow if no more comments are given

**Pull request merged**
