### PR TITLE
Math: restore sin_lookup - used by OSD

### PR DESCRIPTION
**Pull request by peabody124**
As requested splitting appart #2120 

This was previously in the code and used.

### CODE REVIEW

**Comment by kubark42** [comment]
Thanks! If I wrote a unit test for this, could we get in for the PR?

**Comment by peabody124** [comment]
Sound like a good idea

**Comment by mlyle** [comment]
Is there even any reason for this?  brainfpv/dRonin moved to just use sinf.

Sure, this is a few cycles faster, but uses a lot of flash, trades off precision (to single degree), and it's done just a few times per frame (vs. the thousands of sinf's we do per second in core flight control).

**Comment by peabody124** [comment]
Flash is pretty cheap and we dont need more accuracy

**Comment by mlyle** [comment]
Yes, but what is the benefit from this?  It wastes precision, adds more code to maintain, and is an undetectable optimization in CPU used.

**Comment by peabody124** [comment]
@mlyle fair point. updated OSD to use sinf and no problems. I'll close this.

**Comment by kubark42** [comment]
Cool, glad to see agreement. I'm fine either way as there's no clear "perfect" answer.

**Pull request closed without merging**
