### PR TITLE
gcs: eliminate SystemIdent save error

### PR DESCRIPTION
**Pull request by mlyle**
This has been a frequent support annoyance and has confused me too.   Confirmed to fix.

### CODE REVIEW

**Comment by fujin** [comment]
:+1:

**Comment by elafargue** [comment]
Much better, we should definitely merge this ASAP

**Comment by jihlein** [comment]
I think camera stab suffers from the same issue.

**Comment by mlyle** [comment]
Open an issue..  I prioritized this one both because it gets me and a lot of people show up for support with it.

**Comment by jihlein** [comment]
Issue opened, #1653.

**Pull request merged**
