### PR TITLE
Arm: update to 4.9-2015-q1-update

### PR DESCRIPTION
**Pull request by peabody124**
Update to the latest arm sdk

 - [x] test memory changes for Sparky
 - [x] test memory changes for Quanton
 - [x] test memory changes for FlyingF3
 - [x] test memory changes for CC3D

### CODE REVIEW

**Comment by peabody124** [comment]
Tested boards with erased settings. On this branch:

CC3D: heap remaining 2076 irqstatck 212 cpuload 58
FlyingF3: heap 11642 irq 512 cpu 48
Sparky: heap 5902 irq 512 cpu 55
Sparky2: heap 89744 irq 512 cpu 30
Quanton: heap 89760 irq 512 cpu 30

**Comment by peabody124** [comment]
on previous toolchain:

CC3D: heap 2200 irq 164 cpu 61
FlyingF3: heap 11674 irq 512 cpu 50
Sparky: heap 6034 irq 512 cpu 62
Sparky2: heap 89752 irq 512 cpu 28
Quanton: heap 89828 irq 512 cpu 31

**Comment by peabody124** [comment]
Overall no major changes in resource utilization. Maybe it has a few less free bytes of heap. I think we should merge it.

Other thoughts? @elafargue  @brainfpv

**Comment by lilvinz** [comment]
I am puzzled. Which version are you trying to update to? 2014q4 or 2015q1?

**Comment by peabody124** [comment]
@lilvinz sorry forgot to push latest commit. done now.

**Comment by lilvinz** [comment]
jenkins: test this please

**Comment by peabody124** [comment]
jenkins: test this please

**Comment by elafargue** [comment]
I am getting pretty different (and better) figures on Sparky with the new toolchain, any reason ?

Sparky: heap: 8456  cpu: 37%

**Pull request merged**
