### PR TITLE
Txpid add path follower tuning

### PR DESCRIPTION
**Pull request by kubark42**
This PR would help with #1838 .

Note, it is not compatible with targets that do not include the VTOLPathFollowerSettings UAVO (and thus Jenkins should fail to build). If the functionality is of interest beyond helping out with #1838, it should be easy to include.

### CODE REVIEW

**Comment by mlyle** [comment]
I'd like it if we can merge this in general-- so it'd be nice if we could conditionalize the flight code on the presence of the UAVO.

One thing to be aware of-- we're in the later phases of functional work on this release.  https://github.com/TauLabs/TauLabs/wiki/Endomorphism-(September)-release

I love this stuff that's coming in, but I'm going to have to taper off merging it as we've already incurred a lot of risk and we're at the tail end.  So some of this stuff may need to be deferred to the next.  (I'm going to do my best to get in what I can).

**Comment by kubark42** [comment]
Understood and agreed. I've only been pushing bug fixes because, hey, who doesn't love a good bugfix before release?

I labeled this "PR for comment", I don't expect it to merge. It's work I did earlier to resolve the problem you mention in #1838, so my hopes are that it might be again useful.

**Comment by BrainFPV** [comment]
Nice :).

Maybe we could use and `#if defined(UAVO_NAV)` to conditionally compile in the code on targets that support navigation.

**Comment by mlyle** [comment]
Closed in favor of #1857, which is this fixed up to build on all targets.

**Pull request closed without merging**
