### PR TITLE
python-ins: Move py INS code out of python subtree

### PR DESCRIPTION
**Pull request by mlyle**
Also add GPL notice to README.

### CODE REVIEW

**Comment by peabody124** [comment]
Why?

**Comment by mlyle** [comment]
Because I assume you don't want to relicense it LGPL.

**Comment by peabody124** [comment]
Oh gotcha :) thanks. Ugh, I don't like adding lots of top level directories either though. Good attention to detail though.

@solidgoldbomb any thoughts on organization here?

**Comment by solidgoldbomb** [comment]
I don't think this makes sense as a new top-level directory.

**Comment by mlyle** [comment]
Do you want to move it into flight, because it's generating flight code?

**Comment by mlyle** [comment]
Closed per discussion.

**Pull request closed without merging**
