### PR TITLE
Autotune: document derivation of optimization

### PR DESCRIPTION
**Pull request by peabody124**

### CODE REVIEW

**Comment by tracernz** [comment]
Excellent! LGTM

**Comment by kubark42** [comment]
Don't have time to read it right now, but want to publish the latex code as well?

**Comment by peabody124** [comment]
@kubark42 I initially did and put it in a directory, then suddenly I had to include the images and it didn't seem worth the trouble.

**Comment by kubark42** [comment]
@peabody124 I'd be happy to see the images included, but I think it'd be fine without.

**Comment by tracernz** [comment]
You couldn't export the plots in eps format? That should knock the size down a bit and pdflatex knows how to handle them with the added advantage that they'll be rendered in vector format.

**Comment by tracernz** [comment]
@peabody124 Are you going to add any more to this or should we merge as-is?

**Comment by peabody124** [comment]
I probably won't do more on this, so I'd say merge as is. If people really want the raw tex they can email me.

**Pull request merged**
