### PR TITLE
State estimation: Fix complementary filter heading initialization

### PR DESCRIPTION
**Pull request by kubark42**
The initialization math required that the vehicle be level. This limitation was non-obvious, and probably why the error was made.

### CODE REVIEW

**Comment by mlyle** [comment]
Is this root cause for #908 / #917?

**Comment by kubark42** [comment]
I doubt it's the root cause, but it might have been the initial clang that got the system ringing. The issue in #917 was that the convergence routine can drive the system unstable, even though the system is demonstrated to mathematically converge under (almost) all conditions. That indicates that a more adaptive/less aggressive convergence scheme would converge foar a wider range of bad initial values.

P.S. I discovered this thanks to the visualization in #1906.

**Comment by mlyle** [comment]
I'm not in favor for this for endomorphism.  Is this OK?

**Comment by peabody124** [comment]
It also might be worth making this a library method that creates the initial quaternion based on mag/acceleration abd use that from the ins on it code as we repeat essential the same thing.

I haven't reviewed this but i prefer it to turning off gyro bias estimation during init.

**Comment by kubark42** [comment]
> I'm not in favor for this for endomorphism. Is this OK?

Fine by me, I've been using the fix for a year now. ;)

@peabody124 Good idea for making this a library. Although we shouldn't confuse this theoretical bug with the gyro bias initialization instability.

**Comment by mlyle** [comment]
OK, I've read this and it pretty obviously is correct.

**Pull request merged**
