### PR TITLE
Flight: Clarify arming configuration, warn when throttle not checked

### PR DESCRIPTION
**Pull request by peabody124**
Add +Throttle to all options which check throttle position.
Add a warning in GCS when an option which doesn't check throttle is selected.
Clarify label on arming option combobox.

From https://github.com/d-ronin/dRonin/pull/255

### CODE REVIEW

**Comment by peabody124** [comment]
This is based on some cases of people not realizing certain arming modes did
not require throttle checks, and thus makes it more explicit. This will have the down
side of breaking manual control settings for the next release, but seems worthwhile
for a more conservative interface.

**Comment by kubark42** [comment]
If we're going to break ManualControlSettings, can we please, please split it into a RxTransmitter object and an "everything else" object? It seems crazy that we have to make people redo a transmitter calibration because we've added an option for how to arm the vehicle.

**Comment by peabody124** [comment]
@kubark42 can you create an issue and we can make that a separate issue? It looks pretty plausible to have these fields in another object, though:

```
               <!-- Note these options should be identical to those in StabilizationDesired.StabilizationMode -->
                <field name="Stabilization1Settings" units="" type="enum" elementnames="Roll,Pitch,Yaw" options="None,Rate,Attitude,AxisLock,WeakLeveling,VirtualBar,Horizon,MWRate,SystemIdent,POI,CoordinatedFlight,AcroPlus" defaultvalue="Attitude,Attitude,Rate"/>
                <field name="Stabilization2Settings" units="" type="enum" elementnames="Roll,Pitch,Yaw" options="None,Rate,Attitude,AxisLock,WeakLeveling,VirtualBar,Horizon,MWRate,SystemIdent,POI,CoordinatedFlight,AcroPlus" defaultvalue="Attitude,Attitude,Rate"/>
                <field name="Stabilization3Settings" units="" type="enum" elementnames="Roll,Pitch,Yaw" options="None,Rate,Attitude,AxisLock,WeakLeveling,VirtualBar,Horizon,MWRate,SystemIdent,POI,CoordinatedFlight,AcroPlus" defaultvalue="Attitude,Attitude,Rate"/>

                <!-- Note these options values should be identical to those defined in FlightMode -->
                <field name="FlightModeNumber" units="" type="uint8" elements="1" defaultvalue="3"/>
                <field name="FlightModePosition" units="" type="enum" elements="6" options="Manual,Acro,Leveling,MWRate,Horizon,AxisLock,VirtualBar,Stabilized1,Stabilized2,Stabilized3,Autotune,AltitudeHold,PositionHold,ReturnToHome,PathPlanner,TabletControl,AcroPlus" defaultvalue="Manual,Stabilized1,Stabilized2,Stabilized3,ReturnToHome,PositionHold"/>
```

**Comment by peabody124** [comment]
Also confirmed no missing copyright headers (#2132 brings in the header on transmitter_control.c)

**Comment by kubark42** [comment]
> @kubark42 can you create an issue and we can make that a separate issue?

Totally. Is it okay to hold off a few days on merging this? My idea is that we minimize the window when users might have to recalibrate their controllers a first and then a second time. If you'd like this to go in now, though, I'd say just go ahead and merge it.

**Comment by peabody124** [comment]
@kubark42 can we merge this?

**Pull request merged**
