### PR TITLE
python: relicense python code to LGPL 2.1 or later

### PR DESCRIPTION
**Pull request by mlyle**
python: relicense python code to LGPL 2.1 or later

Signed-off-by: Michael Lyle <mlyle@lyle.org>
Signed-off-by: Stacey Sheldon <stac@solidgoldbomb.org>
Signed-off-by: James Cotton <peabody124@gmail.com>

### CODE REVIEW

**Comment by mlyle** [comment]
Sorry about the initial title.

Based on this authorship history:

Michaels-MBP:taulabs mlyle$  git log python/taulabs | grep Author | sort -u
Author: James Cotton <peabody124@gmail.com>
Author: Michael Lyle <mlyle@lyle.org>
Author: Stacey Sheldon <stac@solidgoldbomb.org>

Michaels-MBP:taulabs mlyle$ git log -1 | head -4
commit 2dc0aa40d4b4da74fd294b1230c4865d4d2316e2
Merge: 3d4336e 722ac0b
Author: peabody124 <peabody124@gmail.com>
Date:   Mon Jun 8 23:03:16 2015 -0500

**Comment by mlyle** [comment]
I am, obviously, as initiator, fine with this change.

**Comment by BrainFPV** [comment]
+1 For this change

**Comment by peabody124** [comment]
I'm ok with this change.

**Comment by peabody124** [comment]
jenkins: test this please

**Comment by solidgoldbomb** [comment]
I'm OK with this change.  That covers all authors of this code.  Merging.

**Comment by mlyle** [comment]
Cool!  Thank you everyone.

**Pull request merged**
