### PR TITLE
TauLinkModule: updated BOM

### PR DESCRIPTION
**Pull request by thunderdan**
- updated to in-stock part for I2
- added part number for rf22b module
- added info for BLE module
- cleaned up

Signed-off-by: thunderdan thunderdanmorgan@gmail.com

### CODE REVIEW

**Comment by kubark42** [comment]
Jenkins, test this please.

**Comment by thunderdan** [comment]
Thanks Ken. This patch is an update to the XLS file for the tau link module bill of materials.  

If that breaks the bill then just delete me from the project now 😄

It would probably make more sense for someone that is interested in the tau link module to do a review.

-- Dan Morgan --

**Comment by kubark42** [comment]
Thanks, @thunderdan. With your comments in mind, I think @peabody124 would be best to merge this.

**Comment by peabody124** [comment]
@thunderdan thanks for opening this. Could you keep the file name v0.2 as that corresponds to the hardware version. Then should be good to merge.

**Comment by thunderdan** [comment]
I put the BOM file name back to v0.2 as requested.

**Pull request merged**
