### PR TITLE
Flight: FrSky Sport Telem modifications to match FrSky Sensor Hub

### PR DESCRIPTION
**Pull request by jihlein**
Modifications to FrSky Sport Telem to match FrSky Sensor Hub rpm, t1, and t2 values.  This module has been tested to compile, link, and run, but I can't verify operation due to lack of FrSky Sport Telem compatible receivers,

### CODE REVIEW

**Comment by xdandys** [comment]
This looks good. Give me day or two and i will test it. 

This also leads me to think about more meaningful usage of other telemetry fields. For example AccX, AccY, AccZ. It's currently mapped to raw accelerometer outputs. It actually have very limited information value when you consider how noisy accelerometers are and how low sample rate we can achieve with frsky telemetry. What about map them to attitude roll, pitch, yaw angles instead? It would for example allow us to have some fancy custom lua telemetry screen with artificial horizon on Taranis.

**Comment by peabody124** [comment]
@xdandys there already is an NEDAccel object, although we might have stopped using it. It is the LPF version of acceleration in a north/east/down frame.

**Comment by mlyle** [comment]
I don't think he means nedaccel, he means to take attitudeactual.

**Comment by xdandys** [comment]
Ok, I've just tested this and it's working as expected.

**Comment by mlyle** [comment]
Merging based on positive test feedback and that it's same as other code.

**Comment by lolorc** [comment]
@xdandys something like this ? https://github.com/TauLabs/TauLabs/compare/next...lolorc:frsky_sport-encode_angle
I've never PR'ed it because I wanted it to be runtime configurable, and I never spent the time adding a new object...

**Pull request merged**
