### PR TITLE
remove REVOLUTION define from all modules / targets

### PR DESCRIPTION
**Pull request by mlyle**

### CODE REVIEW

**Comment by peabody124** [comment]
Removing outdated inappropriately named variable: nice

Can you confirm that simulation still flies and that you can get it to not have an error in configuration.

**Comment by mlyle** [comment]
@peabody124 made me nervous there! I thought you'd seen something wrong.

I just built my killrevolutiondefine branch and it flies/navigates fine, at least for minimal cases.

**Comment by peabody124** [comment]
Just wanted to confirm it since I remembered those flags having a hook for simulation at some point. Thanks for doing so!

**Comment by mlyle** [comment]
Of course, thanks for the merge!

**Pull request merged**
