### PR TITLE
Autotune update

### PR DESCRIPTION
**Pull request by peabody124**
This updates the autotune code in a few ways:
- for F3/F4 targets improves the state estimate model for yaw to include a direct torque component
- for F1 targets drops yaw estimation entirely which reduces the CPU load

This code also provides the substrate that is used for the LQG controller I've been working on
but keeps this part somewhat modular.

I've tested the 2D version (no yaw) on Sparky2 and it produces the same estimate for roll and
pitch as the full model. I'm trying to get my CC3D up and running but it's giving me some grief
so any testing there would be appreciated. This should dramatically reduce the CPU utilization
on F1 targets and get them running properly again.

F1 multiplies before: 555
F1 multiplies after: 284

As well as a big reduction in memory requirements.

### CODE REVIEW

**Comment by peabody124** [comment]
Ok test flown on a CC3D, produced sensible AT values and flew nicely afterwards. I will plan to merge this shortly if I don't hear anything.

**Comment by peabody124** [comment]
Oh and most recent F1 multiplies were reduced to 136, so it uses 25% of the calculations it used to.

**Comment by lolorc** [comment]
I have one naze32, and I've never used it, I'll be able to try it next WE on a test quad I'm building.
I should also be able to try this PR with f4 (quanton or revomini) on the same frame.

**Comment by peabody124** [comment]
That would be awesome, thanks

**Comment by peabody124** [comment]
@lolorc any luck? i'd like to merge this shortly.

**Comment by lolorc** [comment]
works perfectly on quanton.
on the naze32 it looks like it failed. while autotuning the quad did stop to shake 2 times for about 2seconds, I thought the autotune was over and then it started shaking again. I stopped after 1min of autototune when it did stop shaking again, results from the autotune tab: https://imgur.com/WUMhPbR
I can try again tomorrow if needed

**Comment by lolorc** [comment]
```
        <object id="0x5E22980C" name="SystemIdent">
            <field name="Tau" values="-4.69132185"/>
            <field name="Beta" values="9.71942711,9.57567978,2.67648007e-43,3.86709402e-34"/>
            <field name="Bias" values="0.0233283602,-0.0191597641,1.08612485e-19"/>
            <field name="Noise" values="1844.98926,1386.04309,3090.33936"/>
            <field name="Period" values="0"/>
            <field name="NumAfPredicts" values="7307"/>
        </object>
```

and 

```
 <object id="0x5E22980C" name="SystemIdent">
            <field name="Tau" values="-4.66644192"/>
            <field name="Beta" values="9.96568203,9.31811619,2.67648007e-43,3.86709402e-34"/>
            <field name="Bias" values="0.0289465878,0.0108112721,1.08612485e-19"/>
            <field name="Noise" values="nan,nan,3467.79932"/>
            <field name="Period" values="0"/>
            <field name="NumAfPredicts" values="7331"/>
        </object>

```

nothing usable from those ATs.
I'll probably give this naze32 board away to a baseflighter ;-)

**Comment by mlyle** [comment]
7.3k estimates; 20k expected at 333Hz, so it's not close to working on F1.

**Comment by mlyle** [comment]
Probably should not have had the F1 specific version if it doesn't do anything useful :/  Just more code to rot.

**Comment by peabody124** [comment]
It worked for me and the existing code definitely doesn't work so that is an improvement, but regardless there are some other improvements coming down the pipeline that builds on this.

**Comment by SaimenSays** [comment]
Due to connection issue in VirtualBox, I'm unable to use actual trunk productive. But I think this pull request will solve wrong autotune of my qudrocopter. So can someone tell me when next release will arrive?

**Comment by mlyle** [comment]
@SaimenSays unfortunately TauLabs development is not super active. 

We've made some significant improvements in autotune in dRonin-- you may want to try our firmware.

(We're also studying the LQG controllers and these changes for possible inclusion in dRonin, along with other approaches).

**Pull request merged**
