### PR TITLE
CopterControl: OneShot and HSUM support

### PR DESCRIPTION
**Pull request by ernieift**
Add PIOS functions for OneShot on F1 targets. Enable OneShot on
CopterControl. Add HoTT receiver support for CopterControl.

### CODE REVIEW

**Comment by peabody124** [comment]
jenkins: test this please

**Comment by ernieift** [comment]
@peabody124 Because autotune is not functional on CC, i reduced the STACK_SIZE_BYTES to 1500 in autotune.c. Would you please check if this ok? Then i could change this line in autotune.c in order to make this working on CC too. Or will you make a PR for this separately.

**Comment by peabody124** [comment]
@ernieift can you make the autotune change a separate PR - best to keep independent issues independent. I'll need to turn on stack diagnostics and check the free space but that sounds like a good solution.

**Comment by ernieift** [comment]
@peabody124 I've opened a separate PR #1495 for this and checked both PR in combination today.

**Comment by ernieift** [comment]
Successfully tested the changes with CC3D and KISS12A today. Works like expected.

**Pull request merged**
