### PR TITLE
rfm22b: Allow selection of hardware band.

### PR DESCRIPTION
**Pull request by peabody124**
For both Tau-style telemetry and OpenLRS.  Initial frequencies chosen
for Tau-style telemetry on 868 and 915 bands.

### CODE REVIEW

**Comment by peabody124** [comment]
See #1803

**Comment by peabody124** [comment]
This has been previous reviewed and written by someone else. We don't have hardware to test this on so should either close or merge this.

**Comment by mluessi** [comment]
@peabody124 has it been verified that 433MHz still works as expected? If so, I vote for merging this.

**Comment by peabody124** [comment]
Yep. I tested this on #1803. Merging then.

**Pull request merged**
