### PR TITLE
makefile: restore parallelism to unix environments

### PR DESCRIPTION
**Pull request by mlyle**
Fixes bug #2051, introduced in #2024

### CODE REVIEW

**Comment by kubark42** [comment]
For those of us unfamiliar with the fiber points of Makefiles, could we get a quick link or explanation for what the + changes?

**Comment by mlyle** [comment]
Presence of $(MAKE) verbatim (not as a subexpansion) in a rule produces various changes of what environment variables are exported, including the stuff necessary for submakes to communicate with the job server.  This was changed to $(GMAKE) by the previous PR-- adding + to the beginning of the rule is an alternate way to trigger the same behavior.

The makefiles need a lot of cleanup and audit; there may be better alternatives ultimately, but this is the minimal fix.

**Comment by tracernz** [comment]
This kind of hidden side-effect is really annoying. :( Relevant docs: https://www.gnu.org/software/make/manual/make.html#MAKE-Variable

**Comment by mluessi** [comment]
+1 for merge

**Comment by PTDreamer** [comment]
I believe I tried this approach and it broke MSVC builds. I have another fix to this same issue on a branch I keep having to rebase https://github.com/TauLabs/TauLabs/commit/09bb3e4e3a94e3bfc3972228478311f850a12d0b
Since this is a small change I wont mind having to fix the rebase again, and deal with possible issues.
The branch I referred is for a GCS autoupdater and since I'm currently dealing with OSX I wont have time to test this with MSVC this next few days.

**Comment by peabody124** [comment]
@PTDreamer since you reported the original bug, can you confirm this fixes it?

**Comment by peabody124** [comment]
screen shot 2015-11-15 at 9 54 20 am

Output on parallel builds looks odd for a time

**Comment by mlyle** [comment]
That's the uavobject libraries.  They don't currently set a target name.

**Comment by PTDreamer** [comment]
> @PTDreamer since you reported the original bug, can you confirm this fixes it?

Not only I reported but I also created it.
@mlyle can you have a look at the commit I referred above and see if you agree with that approach? The thing is that I believe I tried the "+" since it is the most usual way and it broke MSVC compile as far as I can remember.

**Comment by mlyle** [comment]
I'm fine with that approach.

It really sucks to not have fast parallel builds in the meantime though.

**Pull request closed without merging**
