### PR TITLE
revomini: adjust flash partitioning, enable picoc

### PR DESCRIPTION
**Pull request by mlyle**
Corrects #1801.  RELNOTE: Requires new bootloader.

Now consistent with Quanton and Sparky2.

Needs test; when my revomini shows up I'll give it a whirl.

### CODE REVIEW

**Comment by peabody124** [comment]
So the only issue with this is that it makes it harder for people to jump back and forth between TL and OP/LP. I'm not sure if picoC (for those users) would be worth the increased barrier to entry.

I'm not particularly against this, just laying out the pros/cons.

**Comment by mlyle** [comment]
Does the new bootloader prevent loading old OP images?

It looks like OpenPilot raised it to a 640k limit in 2003: https://github.com/openpilot/OpenPilot/blob/master/flight/targets/boards/revolution/board-info.mk

**Comment by mlyle** [comment]
That should be 2013. :P

**Comment by peabody124** [comment]
Oh, then I'm less sure. Should be tested - maybe they aren't even compatible anymore but I don't think that is the case.

**Comment by mlyle** [comment]
Confirmed to boot and work with OP bootloader.

**Comment by mlyle** [comment]
Confirmed to boot and work with TL bootloader.  Spotted an issue where ccache doesn't know about bootloader bin includes.. need to fix.

**Comment by mlyle** [comment]
That is , to boot and work with -new- TL bootloader.

**Pull request merged**
