### PR TITLE
naze32: add serial support

### PR DESCRIPTION
**Pull request by mlyle**
Resolves issue #1819.

Depends on PR #1828.

Completely untested so far.  Just the code / compiles.

### CODE REVIEW

**Comment by mlyle** [comment]
Confirmed it initializes the DSM driver IFF rcvrport == PPM+Serial and rcvrserialport == DSM.

Need to figure out what's easiest to wire up-- maybe a GPS-- and smoke test.

**Comment by mlyle** [comment]
Verified that it outputs mavlink on ch3 at 57600.  I'm callin' that good.

**Comment by tracernz** [comment]
Verified to worked for DSM as well.

**Comment by mlyle** [comment]
Niiiiice.

**Pull request merged**
