### PR TITLE
flight: remove a bunch of uncompiled code.

### PR DESCRIPTION
**Pull request by mlyle**
Things skipped in this pass:   Fault, overo_sync, sim console, pios_udp
sim code, pios_hcsr04 pios_hmc5843 pios_hmc5983 pios_hmc5983_i2c
pios_pcf8591_adc

### CODE REVIEW

**Comment by kubark42** [comment]
Jenkins is not pleased.

**Comment by mlyle** [comment]
Yup, will examine, i did send htis one blind.

**Comment by mlyle** [comment]
Fixed up now, pipxtreme included some files it shouldn't have (It doesn't need to control I2C ESC's ;)

**Comment by peabody124** [comment]
Also LGTM. Nice LOC balance :)

I'll leave merge this shortly unless @kubark42 wants to comment on some of the old state estimation filters

**Pull request merged**
