### PR TITLE
Save stack space in mavlink bridge

### PR DESCRIPTION
**Pull request by mlyle**
For issue #633.  @SystemsGuy generously bench-tested, and found it to work but heap was very low.  This gets us some more bytes.  Needs verification that it still works.

### CODE REVIEW

**Comment by peabody124** [comment]
how much is free when it is running? typically it is nice to keep a margin of at least 50 bytes so we don't get surprise segfaults

**Comment by peabody124** [comment]
logic looks good, moving variables into local scope is sensible and having explicit defaults is not that useful

**Comment by mlyle** [comment]
When I've done refactors like this, I've slightly increased the amount free.  I didn't measure this.  Static analysis says the task function uses 112 bytes less (from gcc -fstack-usage), so I turned down the task stack by 104 bytes.  There should be 8 more bytes free.

Ultimately I'd like to put together a tool that looks at the entire call graph and data from -fstack-usage and comes up with a worst-case number for a task.  But now the only tool I have in my toolbox is to look at functions that I know are in the worst-case stack usage path (and a task's main function certainly falls in that category) and look at their change.

Note the explicit defaults are still present-- assigning the structure to {} is equivalent to the previous initialization.

**Comment by mlyle** [comment]
Rebased due to merge conflict.

Artifact at http://jar.lyle.org/~mlyle/TauLabs-20150189-4e6ab8ca-install.exe

**Comment by SystemsGuy** [comment]
Bench tested on CC3D with  MinimOSD-Extra_Copter_Pre-release_2.4_r726 , seems to be working fine, flight modes as well.

mavlink-tau labs gcs_2015-08-21_23-15-41

**Comment by mlyle** [comment]
Woot! 480 bytes free.  That's happiness right there.

Thanks @systemsguy!

**Pull request merged**
