### PR TITLE
Naze: Tidy up and remove commented code from startup

### PR DESCRIPTION
**Pull request by tracernz**
This just cleans up a small little mess I left behind when writing the Naze DFU code.

### CODE REVIEW

**Comment by tracernz** [comment]
I decided while I'm at it to reorder the code slightly to keep all the DFU code together.

**Comment by mlyle** [comment]
I see no reason why changing a branch and reordering the code would cause a problem.

That being said, has this been tested?

**Comment by tracernz** [comment]
Sorry, forgot to mention. Yes I have tested it. :)

**Comment by mlyle** [comment]
OK I'm happy :)

**Pull request merged**
