### PR TITLE
pios_thread: chibios requires 8 byte boundary for stacks

### PR DESCRIPTION
**Pull request by peabody124**
This was causing the GPS module to crash because 850 stack size.
The new function always computes a stack size that is aligned
to a multiple of 8 and has a size that is a multiple of 8 at
least as large as requested.

### CODE REVIEW

**Comment by peabody124** [comment]
fixes #1516

**Comment by lolorc** [comment]
I've just tried that on one of my quanton, been able to flash fw with bl84. thanks

**Comment by elafargue** [comment]
Tested on Sparky - Battery stack space is a bit worrying (4 bytes) ?

**Comment by peabody124** [comment]
@elafargue check #1519 regarding battery issue

**Pull request merged**
